### ISSUE TITLE
Cannot read property 'compileOptions' of undefined

### ISSUE THREAD

**Issue by kdabo** [rekow/sass-stream#2]
Hi @davidrekow,
When executing the example provided on the documentation of this project as described below:

```
var sass = require('sass-stream'),
    fs = require('fs');

// As an intermediary step in a flow
fs.createReadStream('sprites')
    .pipe(sass())
    .pipe(fs.createWriteStream('css/stylesheet1.css'));

// As the terminus in a flow
fs.createReadStream('sprites')
    .pipe(sass({
        output: 'css/stylesheet1.css'
    }));
```

I'm stuck with the the following error:

```
$ node sass-stream.js 
/.../node_modules/sass-stream/index.js:64
        compileOpts = opts.compileOptions || {},
                          ^
TypeError: Cannot read property 'compileOptions' of undefined
    at module.exports (/.../node_modules/sass-stream/index.js:64:27)
    at Object.<anonymous> (/.../sass-stream.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I'm not sure how to deal with this error, do you have any suggestions ?

Thank you in advance.

**Comment by kdabo** [comment]
Although it may seen obvious that the error is due to no params passed to the function saas(), when I do it, eg: `.pipe(sass({}))` I'm then stuck with another meanless error:

```
$ node sass-stream.js 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EISDIR, read
    at Error (native)
```

Not sure, is this because he can't find the scss ? 
Thank you.

**Comment by kdabo** [comment]
When I correct all this errors (at least it looks like the absolute paths are correct)

I get into another error:

```
var sass = require('sass-stream'),
    fs = require('fs'),
    path = require('path');

var dir = path.join(__dirname, '/sprites/scss/_sprites.scss')
console.log(dir)

var dest = path.join(__dirname, '/css/style.css');
console.log(dest);

// As an intermediary step in a flow
fs.createReadStream(dir)
    .pipe(sass({}))
    .pipe(fs.createWriteStream( dest));
```

error:

```
$ node sass-stream.js 
.../sprites/scss/_sprites.scss
.../css/karai.css
node(99192,0x7fff7023acc0) malloc: *** error for object 0x10296b040: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap
```
